### ISSUE TITLE
投稿用フォーム作成

### ISSUE THREAD

**Issue by takuuuu517** [takuuuu517/nuxt-sample-app#1]
## ゴール
フォームに書いた内容をボットから投稿するようにする。

### 問題点
- 現状、人が投稿した内容を読むだけになっていて、ボットから発信する機能が備わっていないため。

### 理由
- このボットがそのチャンネル内で特定の役割を果たし、使用者に何かを通知しないといけない場合、ボットから発信できるようになる。

## 仕様要件
- フォームの入力可能文字数
  - 4,000文字 ([ref](https://api.slack.com/methods/chat.postMessage#text_usage))

- フォームの送信ができるユーザー
  - ブラウザのページにアクセスできるユーザー

- 送信できるのは
  - 文字のみ

- リンクが文字列に含まれるときは
  - クリックして、ブラウザの新しいウィンドウできるようにする (ブラウザ上/ slack上)

- 画像のリンクが文字列へ含まれるとき
  - 画像が見えるようにする (ブラウザ上/ slack上)
  - イメージタグに直接画像のパスを指定して表示させる。
  - クリックして、ブラウザの新しいウィンドウできるようにする (ブラウザ上/ slack上)

- ファイルアップロード機能
  - なし

## 完了条件
- [x] テキストフォームに文字を入力して、送信ボタンを押すと、メッセージがスラックのチャンネルに投稿される。
- [x] chat.postMessageによってメッセージの投稿が成功した場合にブラウザでは、投稿したメッセージが表示される。
- [x] メッセージの投稿が失敗した場合、エラーメッセージをアラート表示させる。
- [x] コンソール上にエラーメッセージが出ないようにする。

## TODO
- [x] バグ修正
- [x] vuetifyのページネーションコンポーネントのバグの修
- [x] textfield を作る
- [x] textfieldにURL、画像のリンクが文字列に含まれるときはクリックしたらブラウザの新しいタブできるようにする
- [x] フォームの入力可能文字数の制限をつける
- [x] 送信ボタンの作成

**Comment by snkrheadz** [comment]
@takuuuu517 質問です、

- フォームの入力可能文字数は何文字ですか？
- フォームの送信ができるユーザーは誰ですか？
- 送信できるのは、文字だけですか？
- リンクが文字列に含まれるときはどのようになりますか？
- 画像のリンクが文字列へ含まれるときはどうなりますか？
- ファイルアップロード機能はあ李ますか？
